### CONSTRUÇÃO E ANÁLISE DE CARTEIRA DE AÇÕES

#### Carregando as Bibliotecas

In [1]:
import numpy as np
import pandas as pd
import pandas_datareader.data as wb
import matplotlib.pyplot as plt
import statsmodels.api as sm
import scipy.stats

#### Obtendo os Dados do Ibov e das Ações

In [2]:
tickers = ['^BVSP','AGRO3.SA','BBAS3.SA','BBDC3.SA','BBDC4.SA','BBSE3.SA','CMIG4.SA','CPLE6.SA','CSMG3.SA','ITSA4.SA','ITUB4.SA','PSSA3.SA','SAPR3.SA','TAEE11.SA','VIVT3.SA']
data = pd.DataFrame()
for t in tickers:
    data[t] = wb.DataReader(t,data_source='yahoo',start='2019-1-1')['Adj Close']

data.tail()

,^BVSP,AGRO3.SA,BBAS3.SA,BBDC3.SA,BBDC4.SA,BBSE3.SA,CMIG4.SA,CPLE6.SA,CSMG3.SA,ITSA4.SA,ITUB4.SA,PSSA3.SA,SAPR3.SA,TAEE11.SA,VIVT3.SA
Date,,,,,,,,,,,,,,,
2022-09-19,111824.000000,30.260000,40.180000,16.059999,19.530001,29.809999,11.70,6.76,13.418261,9.56,27.680000,22.60,3.27,40.939999,40.990002
2022-09-20,112517.000000,30.070000,40.790001,16.650000,20.160000,30.219999,11.67,6.76,13.695130,9.83,28.600000,22.90,3.28,41.299999,41.049999
2022-09-21,111936.000000,30.389999,40.500000,16.540001,20.040001,30.080000,11.62,6.71,13.680000,9.78,28.299999,22.33,3.33,41.660000,41.110001
2022-09-22,114070.000000,30.990000,41.240002,16.870001,20.500000,29.639999,11.93,6.89,13.880000,9.99,28.870001,22.58,3.41,41.770000,42.250000
2022-09-23,111271.210938,30.660000,40.639999,16.400000,20.000000,29.480000,11.81,6.83,13.650000,9.71,28.139999,22.16,3.42,41.669998,41.840000

#### Calculo dos Rettornos

In [3]:
retornos = np.log(data / data.shift(1))
retornos.tail()

,^BVSP,AGRO3.SA,BBAS3.SA,BBDC3.SA,BBDC4.SA,BBSE3.SA,CMIG4.SA,CPLE6.SA,CSMG3.SA,ITSA4.SA,ITUB4.SA,PSSA3.SA,SAPR3.SA,TAEE11.SA,VIVT3.SA
Date,,,,,,,,,,,,,,,
2022-09-19,0.023013,0.002979,0.019604,0.023946,0.025410,0.011471,0.027731,0.004448,-0.014631,0.029726,0.036796,0.001772,-0.006098,0.007109,0.008821
2022-09-20,0.006178,-0.006299,0.015068,0.036079,0.031749,0.013660,-0.002567,0.000000,0.020424,0.027851,0.032697,0.013187,0.003053,0.008755,0.001463
2022-09-21,-0.005177,0.010586,-0.007135,-0.006628,-0.005970,-0.004643,-0.004294,-0.007424,-0.001105,-0.005099,-0.010545,-0.025206,0.015129,0.008679,0.001461
2022-09-22,0.018885,0.019551,0.018107,0.019755,0.022695,-0.014736,0.026329,0.026472,0.014514,0.021245,0.019941,0.011133,0.023740,0.002637,0.027353
2022-09-23,-0.024842,-0.010706,-0.014656,-0.028256,-0.024693,-0.005413,-0.010110,-0.008746,-0.016709,-0.028428,-0.025611,-0.018776,0.002928,-0.002397,-0.009752

#### Gerando a Matriz de Correlação

In [20]:
correlacoes = retornos.corr()
correlacoes['^BVSP']

^BVSP        1.000000
AGRO3.SA     0.375322
BBAS3.SA     0.827228
BBDC3.SA     0.826547
BBDC4.SA     0.809628
BBSE3.SA     0.615032
CMIG4.SA     0.735457
CPLE6.SA     0.678871
CSMG3.SA     0.596707
ITSA4.SA     0.806649
ITUB4.SA     0.751505
PSSA3.SA     0.509615
SAPR3.SA     0.466968
TAEE11.SA    0.527906
VIVT3.SA     0.462665
Name: ^BVSP, dtype: float64